// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setChirpyRedUserByID = `-- name: SetChirpyRedUserByID :exec
UPDATE users
SET is_chirpy_red = $2
WHERE id = $1
`

type SetChirpyRedUserByIDParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

func (q *Queries) SetChirpyRedUserByID(ctx context.Context, arg SetChirpyRedUserByIDParams) error {
	_, err := q.db.ExecContext(ctx, setChirpyRedUserByID, arg.ID, arg.IsChirpyRed)
	return err
}
